### ISSUE TITLE
Xiaomi Speaker: unable to call action 小爱音箱无法静默执行指令

### ISSUE THREAD

**Issue by EliLaputaLab** [al-one/hass-xiaomi-miot#2630]
### Device model / 设备型号

xiaomi.wifispeaker.lx06

### Component version / 插件版本

1.0.21

### HA core version / HA版本

2025.9.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Unable to call action after updating to 1.0.21.
更新到 1.0.21 后，无法执行 xiaomi_miot.intellegent_speaker 动作。提示：error: "'Device' object has no attribute 'call_action'"

<img width="2448" height="1506" alt="Image" src="https://github.com/user-attachments/assets/346b393f-1a7f-4e25-98f4-f616f3605b13" />

### Entity attributes / 实体属性

```yaml
button.info: Mi AI Speaker Pro
model: xiaomi.wifispeaker.lx06
did: 
mac: 
lan_ip: 
app_link: 
miot_type: urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx06:2
available: true
home_room: 
icon: mdi:information
updater: cloud
updated_at: "2025-09-14 15:43:59.402324+08:00"
speaker.volume: 36
speaker.mute: true
microphone.mute: false
intelligent_speaker.sleep_mode: false
intelligent_speaker.audio_id: ""
state_updater: cloud
xiaoai_id: 
converters:
  - button.info
  - switch.intelligent_speaker.sleep_mode
  - button.intelligent_speaker.play_music
  - button.intelligent_speaker.wake_up
  - button.clock.stop_alarm
  - text.intelligent_speaker.play_text
  - text.intelligent_speaker.execute_text_directive
customizes:
  switch_properties: on,sleep_mode,no_disturb
  button_actions: wake_up,play_music,tv_switchon,stop_alarm
  text_actions: play_text,execute_text_directive
  interval_seconds: "3"
info: null
device_class: update
friendly_name: 小爱音箱 信息
```

**Comment by Cook23** [comment]
Same problems for all my vacuum devices

**Comment by PGayol** [comment]
> Same problems for all my vacuum devices

Same here on my Xiaomi MIjia 1C since last update.
