### ISSUE TITLE
viomi.v8 unavailable

### ISSUE THREAD

**Issue by Melaxx19** [al-one/hass-xiaomi-miot#2328]
### Device model / 设备型号

viomi.vacuum.v8

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Device with all entities are offline in HA, cannot start it either. The vacuum is accessible via Xiaomi Home app.
Let me know if you need more info/details. I will be happy to provide everything all you need.

### Entity attributes / 实体属性

```yaml
info: Viomi V8
model: viomi.vacuum.v8
did: 
mac: 5C:6B:D7:08:82:33
lan_ip: 192.168.89.8
app_link: 
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:viomi-v8:1
available: true
home_room: 
icon: mdi:information
updater: none
updated_at: 
converters: button.info, sensor.battery_level, sensor.vacuum.status, sensor.viomi_vacuum.main_brush_life, sensor.viomi_vacuum.side_brush_life, sensor.viomi_vacuum.hypa_life, sensor.viomi_vacuum.mop_life, select.vacuum.mode, button.vacuum.start_sweep, button.vacuum.stop_sweeping, button.vacuum.start_sweep_mop, button.vacuum.start_mop, button.vacuum.pause_sweeping, button.battery.start_charge, sensor.clean_area, sensor.clean_time
customizes: 
binary_sensor_properties: mop_status
sensor_properties: vacuum.status,main_brush_life,side_brush_life,hypa_life,mop_life
select_properties: mode,sweep_mop_type,sweep_type,clean_times
number_properties: volume
button_actions: >-
  start_sweep,stop_sweeping,stop_and_gocharge,start_only_sweep,start_mop,start_sweep_mop,pause_sweeping,continue_sweep,start_dust_arrest,start_mop_wash,start_dry,start_eject,stop_mop_wash,stop_dry,back_mop_wash,start_charge,identify,reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
configuration_entities: reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
chunk_coordinators:
  - interval: 10
    props: status,cleaning_area,cleaning_time,charging_state
    notify: true
  - interval: 15
    props: mode,sweep_mop_type,sweep_type,clean_times
sensor_attributes: clean_area,clean_time

device_class: update
friendly_name: Viomi V8 Info
```

### Home Assistant Logs / 系统日志

ogger: custom_components.xiaomi_miot.core.device.viomi.vacuum.v8
Zdroj: helpers/update_coordinator.py:379
Integrácia: Xiaomi Miot Auto ([dokumentácia](https://github.com/al-one/hass-xiaomi-miot), [problémy](https://github.com/al-one/hass-xiaomi-miot/issues))
Prvýkrát sa vyskytol: 23. januára 2025 o 01:14:03 (2 výskytov)
Naposledy prihlásený: 16:59:39

Unexpected error fetching 5c:6b:d7:08:82:33-chunk_1 data
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
                 ~~~~~~~~~~^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 513, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 827, in update_miot_status
    results = await self.miio2miot.async_get_miot_props(self.local, mapping)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 112, in async_get_miot_props
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        partial(self.get_miot_props, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 120, in get_miot_props
    if dic := self.get_miio_props(device):
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 78, in get_miio_props
    vls = device.send(c['method'], pms)
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 103, in send
    :param dict extra_parameters: Extra top-level parameters
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    :param str model: Force model to avoid autodetection
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    """
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 220, in send
    except construct.core.ChecksumError as ex:
           ^^^^^^^^^^^^^^
AttributeError: module 'construct' has no attribute 'core'

**ALSO:**

ATTR_COLOR_TEMP was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2026.1. Use kelvin equivalent (ATTR_COLOR_TEMP_KELVIN) instead, please report it to the author of the 'xiaomi_miot' custom integration

Detected that custom integration 'xiaomi_miot' is setting state directly. Entity xiaomi_miot.viomi_v8_8233_robot_cleaner (<class 'custom_components.xiaomi_miot.vacuum.MiotViomiVacuumEntity'>) should implement the 'activity' property and return its state using the VacuumActivity enum at custom_components/xiaomi_miot/vacuum.py, line 70: async_add_entities(entities, update_before_add=True). This will stop working in Home Assistant 2026.1, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

STATE_DOCKED was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2026.1. Use VacuumActivity.DOCKED instead, please report it to the author of the 'xiaomi_miot' custom integration
STATE_RETURNING was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2026.1. Use VacuumActivity.RETURNING instead, please report it to the author of the 'xiaomi_miot' custom integration
STATE_ERROR was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2026.1. Use VacuumActivity.ERROR instead, please report it to the author of the 'xiaomi_miot' custom integration
STATE_ERROR was used from xiaomi_viomi, this is a deprecated constant which will be removed in HA Core 2026.1. Use VacuumActivity.ERROR instead, please report it to the author of the 'xiaomi_viomi' custom integration
STATE_ERROR was used from xiaomi_viomi, this is a deprecated constant which will be removed in HA Core 2026.1. Use VacuumActivity.ERROR instead, please create a bug report at https://github.com/nergal/homeassistant-vacuum-viomi/issues

/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py:50: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC). self._device_ts: datetime = datetime.utcnow()

/usr/local/lib/python3.13/site-packages/miio/protocol.py:149: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC). class EncryptionAdapter(Adapter):

**Comment by al-one** [comment]
Upgrade HA and this component to the latest version and retry.
