### ISSUE TITLE
No longer available to send command via Developer tools

### ISSUE THREAD

**Issue by arkadiusz-kopicinski** [al-one/hass-xiaomi-miot#2677]
### Device model / 设备型号

Viomi V3

### Component version / 插件版本

v1.1.0

### HA core version / HA版本

2025.10.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hello

I have a script based on send command to change between two maps. After update to version 1.1.0 stopped working. method: set_map doen't work anymore. 

Reverting to version v1.0.24 fixing the issue

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: Viomi V3 Info
button.info: Viomi V3
model: viomi.vacuum.v13
did: ""
mac: C0:E7:BF:24:6D:54
lan_ip: 10.100.10.105
app_link: ""
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:viomi-v13:2
available: true
home_room: ""
updater: local
updated_at: "2025-10-28 15:05:53.394006+01:00"
vacuum.status: 4
vacuum.sweep_type: 0
vacuum.mode: 3
vacuum.fault: 2105
vacuum.wdr_mode: 0
vacuum.door_state: 1
vacuum.contact_state: 0
vacuum-2.contact_state: 15
vacuum-2.contact_state-16: 11
vacuum.mute: 10
battery_level: 100
viomi_vacuum.repeat_state: 0
viomi_vacuum.remember_state: 1
viomi_vacuum.has_map: 1
viomi_vacuum.has_newmap: 0
viomi_vacuum.mop_route: 0
viomi_vacuum.side_brush_life: 35
viomi_vacuum.side_brush_hours: 64
viomi_vacuum.main_brush_life: 67
viomi_vacuum.main_brush_hours: 244
viomi_vacuum.hypa_life: 35
viomi_vacuum.hypa_hours: 64
viomi_vacuum.mop_life: 70
viomi_vacuum.mop_hours: 126
viomi_vacuum.suction_grade: 3
viomi_vacuum.water_grade: 1
viomi_vacuum.consumable_index: 0
viomi_vacuum.clean_room_ids: ""
viomi_vacuum.clean_room_mode: 0
viomi_vacuum.clean_room_oper: 0
viomi_vacuum.map_num: 2
viomi_vacuum.time_zone: -3600
viomi_vacuum.clean_start_time: 0
viomi_vacuum.clean_use_time: 0
viomi_vacuum.clean_area: 0
viomi_vacuum.clean_map_url: ""
viomi_vacuum.clean_mode: 0
viomi_vacuum.clean_way: 0
viomi_vacuum.cur_lang: pl
viomi_vacuum.cur_map_id: 1653215766
order.dnd_enable: 1
order.dnd_start_hour: 23
order.dnd_start_minute: 0
order.dnd_end_hour: 9
order.dnd_end_minute: 0
order.dnd_timezone: -3600
order.timestamp: 0
point_zone.target_point: "[1100,1100]"
map.map_type: 1
map.map_id: 1634202542
map.map_name: map_1
voice.target_voice: ""
voice.cur_voice: ""
voice.download_status: 0
voice.download_progress: 0
converters:
  - button.info
  - sensor.battery_level
  - sensor.vacuum.status
  - sensor.viomi_vacuum.side_brush_life
  - sensor.viomi_vacuum.main_brush_life
  - sensor.viomi_vacuum.hypa_life
  - sensor.viomi_vacuum.mop_life
  - select.vacuum.sweep_type
  - select.vacuum.mode
  - button.vacuum.start_sweep
  - button.vacuum.stop_sweeping
  - button.vacuum.start_charge
  - button.vacuum.start_mop
  - button.vacuum.start_only_sweep
  - button.vacuum.start_sweep_mop
  - button.viomi_vacuum.reset_map
  - button.viomi_vacuum.reset_consumable
  - sensor.clean_area
  - sensor.clean_time
customizes:
  binary_sensor_properties: mop_status
  sensor_properties: vacuum.status,main_brush_life,side_brush_life,hypa_life,mop_life
  select_properties: mode,sweep_mop_type,sweep_type,suction_level,water_level,clean_times
  number_properties: volume
  button_actions: >-
    start_sweep,stop_sweeping,stop_and_gocharge,start_only_sweep,start_mop,start_sweep_mop,pause_sweeping,continue_sweep,start_dust_arrest,start_mop_wash,start_dry,start_eject,stop_mop_wash,stop_dry,back_mop_wash,start_charge,identify,reset_*
  configuration_entities: reset_*
  diagnostic_entities: filter_l*,brush_l*,detergent_l*,dust_bag_l*
  chunk_coordinators:
    - interval: 11
      props: status,charging_state
      notify: true
    - interval: 16
      props: mode,sweep_mop_type,sweep_type,suction_level,water_level
    - interval: 301
      props: filter_l*,brush_l*,detergent_l*,dust_bag_l*
  sensor_attributes: clean_area,clean_time
info: null
state_updater: local
vacuum.status_desc: Charging
```

**Comment by al-one** [comment]
Please provide the script YAML

**Comment by arkadiusz-kopicinski** [comment]
This command I'm using in automation:
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: vacuum.viomi_v13_6d54_robot_cleaner
  method: set_map
  params: 1634202542 <-- this is map ID
```

**Comment by maksp86** [comment]
Same issue, can't send command
got error `error: AsyncMiIO.send() got an unexpected keyword argument 'throw'`

<details>
<summary>Screenshot</summary>. 

![Image](https://github.com/user-attachments/assets/9ab20c54-5673-41f3-9429-c99bba2e80d5)
</details>

Works well on 1.0.24

**Comment by adamsjo** [comment]
Hello, I also can not use send_command anymore since 1.1.0
I use it to start the vacuum cleaner to clean specific rooms.

In 1.0.24 this works:
```
action: xiaomi_miot.send_command
data:
  entity_id: vacuum.viomi_v8_6274_robot_cleaner
  method: set_mode_withroom
  params:
    - 0
    - 1
    - 4
    - 15
    - 14
    - 11
    - 10
```
and reports:
```
result:
  - ok
``` 

In 1.1.0 and 1.1.1 it shows the error instead:
```
error: AsyncMiIO.send() got an unexpected keyword argument 'throw'
``` 

I rolled back now to 1.0.24, but of course i would like to stay up to date.
